apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: eduregistry.azurecr.io/frontend-vue
    newTag: main-20240725070050

commonLabels:
  app: frontend-vue
  environment: dev
