apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: eduregistry.azurecr.io/backend-java
    newTag: main-20240712064746

commonLabels:
  app: backend-java
  environment: dev
